### ISSUE TITLE
makefiles/targets/Darwin/macosx.mk looks for deprecated compiler

### ISSUE THREAD

**Issue by nieder** [DHowett/fauxsu#2]
makefiles/targets/Darwin/macosx.mk hardcodes gcc/g++-4.2, but that compiler was removed from Xcode several years ago.  It should default to clang/clang++, or perhaps just cc/c++ (which currently points to clang).

**Comment by DHowett** [comment]
Fixed!

**Comment by DHowett** [comment]
(Also, a fink package update is going out -- if you'd rather use that!)

**Comment by nieder** [comment]
Excellent.  When ready, please submit the .info at https://sourceforge.net/p/fink/package-submissions/ so it can be reviewed for committing.
